### ISSUE TITLE
Mails

### ISSUE THREAD

**Issue by matiasanu** [garymartin87/videocallshop-api#20]
Terminar de ver los mails, la descripcion de todos los tipos de mails que necesitamos esta en una conversacion de whatsapp del 13 de noviembre. Si la llegaste a perder avisame que te la vuelvo a escribir. Un abrazo!! @garymartin87

**Comment by matiasanu** [comment]
Gary acordate cuando veas el tema de los mails que estaba faltando poner la descripcion. Abrazoo!

**Comment by garymartin87** [comment]
Dale @matiasanu ! Espero mañana poder ponerme un rato con esto, es cuestion de tener 2 horas despejadas y meterle.

**Comment by garymartin87** [comment]
@matiasanu podes probar ?
Te paso lo que definimos:

**Retiro en la tienda y Pago con MercadoPago**
```
Para finalizar su compra deberá pagar la misma a través del siguiente link: <link>.
```

**Retiro en la tienda y: Pago en tienda o Pago en el domicilio**
```Para finalizar su compra deberá acercarse a la tienda <store.name> ubicada en <store.address> para pagar y retirar su pedido.```

**Envio a domicilio y Pago en el domicilio**
```
Ha finalizado su compra, le llegará su pedido al domicilio <purchaseOrder.address>, <purchaseOrder.city>, <purchaseOrder.province> y podrá pagarlo contra entrega en efectivo.
```

**Envio a domicilio  y Pago con MercadoPago**
```
Para finalizar su compra deberá pagar la misma a través del siguiente link: <purchaseOrder.mercadopagoLink>.
Luego le llegará su pedido al domicilio <purchaseOrder.address>, <purchaseOrder.city>, <purchaseOrder.province>.
```

**Envio a domicilio y Pago en tienda**
```
Para finalizar su compra deberá acercarse a la tienda <store.name> ubicada en:
<store.address> para pagar.
Luego le llegará su pedido al domicilio <purchaseOrder.address>, >purchaseOrder.city>, <purchaseOrder.province>.
```

**Comment by matiasanu** [comment]
![WhatsApp Image 2019-12-12 at 9 46 36 AM](https://user-images.githubusercontent.com/50674449/70713455-cc00e580-1cc4-11ea-8668-89830f09f882.jpeg)

**Comment by matiasanu** [comment]
Hola Gary Ahi comence a probar lo de los mails. Vi 2 cosas, debajo de Productos tenemos que agregar tambien la descripcion del producto que en la app se la pedimos obligatoriamente y puede que ahi pongan alguna informacion importante que estaria bueno que tambien le llegue al mail. Y lo otro que vi es que se repite 2 veces Para Finalizar, Para Finalizar. Deberiamos eliminar el primer renglon que dice (Para finalizar siga los siguientes pasos).

**Comment by matiasanu** [comment]
Luego de Store Adress, hay que agregar Store City y Store Province. Asi queda bien completo.

**Comment by garymartin87** [comment]
√ Agregado el comentario
√ Le saque uno de los PARA FINALIZAR
√ La direccion de la store es un campo único, simplemente deberíamos modificarle en la base de datos el texto para que tenga todos los datos.

**Comment by matiasanu** [comment]
- Quedo perfecto Siga los siguientes pasos... y la leyenda abajo.

- Lo de la direccion de las tiendas yo lo manejaria en campos aparte, quizas sea para hacerlo para mas adelante, pero estaria bueno cuando tengamos un panel de control poder filtrar las tiendas que tenemos por provincias o ciudades. Esto estaria atado con la registracion de las tiendas que hoy no la tenemos.
