### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by matiasanu** [garymartin87/videocallshop-api#22]
Faltarian hacer las push notifications para los vendedores de las tiendas. @garymartin87

**Comment by garymartin87** [comment]
@maurocg89 tenemos que coordinar esto.

**Comment by matiasanu** [comment]
Hola como estan? Hoy probe lo de la push y si bien cuando tenes activo el celular a veces sale la push notification recien probe de bloquearlo e ingresar con otro celular y no le sonó al vendedor
