### ISSUE TITLE
Hay un problema con la primera vez que se entra a la cola de la tienda.

### ISSUE THREAD

**Issue by matiasanu** [garymartin87/videocallshop-api#23]
Hola chicos como estan¿? Les paso un problema que estuve teniendo en las ultimas pruebas que hice. Entre como vendedor en La Elena (Usuario laelena@laelenasa.com contraseña sonserios10) y como comprador en otro celular. Lo que esta pasando es que el comprador entra en la cola y te dice que estas en espera pero al vendedor no le figura que esta ese comprador en espera. Luego si cerras la aplicacion y volves a ponerte en espera comprador te lo toma, pero no se porque la 1era vez no aparece. Les pongo el @ a los 2 porque no se quien de los 2 lo tiene que ver. Un abrazo @maurocg89 @garymartin87

**Comment by garymartin87** [comment]
@maurocg89 si cierra y abre la app y aparece debe estar en la app el bug, te lo asigno a vos y cualquier cosa devolvelo.

**Comment by maurocg89** [comment]
Probar en b7 del comprador

**Comment by matiasanu** [comment]
Solucionado
