### ISSUE TITLE
Una Vez que se finalizo orden de compra te figura como que hay una incompleta.

### ISSUE THREAD

**Issue by matiasanu** [garymartin87/videocallshop-api#24]
![WhatsApp Image 2019-12-12 at 10 11 06 AM](https://user-images.githubusercontent.com/50674449/70714991-120b7880-1cc8-11ea-8ba1-d37d2b4d7073.jpeg)
![WhatsApp Image 2019-12-12 at 10 11 06 AM (1)](https://user-images.githubusercontent.com/50674449/70714992-120b7880-1cc8-11ea-98f8-676af0a22c0c.jpeg)

**Comment by matiasanu** [comment]
Maurito no se si me explique bien. Una vez finalizada 1 orden correctamente, al finalizar la llamada salta el cartel como que hay una orden incompleta cuando en realidad no la hay, debe abrir automaticamente una vez finalizada la 1er orden, una segunda orden en blanco. Puede llevar a confusion de que esta incompleta la 1era orden ese cartel. Abrazo!

**Comment by maurocg89** [comment]
Probar en apk build 7 del vendedor

**Comment by matiasanu** [comment]
SOLUCIONADO
