### ISSUE TITLE
Permisos al comprador para GET purchase-orders

### ISSUE THREAD

**Issue by matiasanu** [garymartin87/videocallshop-api#27]

**Comment by garymartin87** [comment]
@matiasanu cerramos este issue con @maurocg89, ahora el comprador puede ver las ordenes de compra. Te lo asigno para que lo pruebes.

**Comment by garymartin87** [comment]
@matiasanu ahora vas a poder ver las ordenes de compras con el comprador no @maurocg89 ?

**Comment by maurocg89** [comment]
Si, ya está para probar

**Comment by matiasanu** [comment]
Hola chicos ahi lo probe y se ve del lado del comprador tambien, lo que si te saca cuando carga cada 7 segundos.. Y tenes que volver a entrar a la orden de compra.

**Comment by maurocg89** [comment]
Probar en apk build 6

**Comment by matiasanu** [comment]
SOLUCIONADO
