### ISSUE TITLE
Como comprador me tira un error al buscar orden de compra

### ISSUE THREAD

**Issue by matiasanu** [garymartin87/videocallshop-api#28]
![WhatsApp Image 2019-12-30 at 10 40 26 AM](https://user-images.githubusercontent.com/50674449/71587791-ebd63d00-2afd-11ea-97e0-ad330c7bd9d3.jpeg)

Cada un tiempo breve se pone a cargar seguramente buscando la orden de compra, queda medio molesto que te ponga "obteniendo orden de compra" y cargando, y luego tira "Hubo un error"

**Comment by maurocg89** [comment]
Este es el mismo que el anterior
https://github.com/garymartin87/videocallshop-api/issues/27

**Comment by garymartin87** [comment]
@matiasanu probá este también

**Comment by matiasanu** [comment]
Hola Chicos como estan? Ahi la probe y no me tira ningun error pero lo que si me muestra es el simbolito cargando cada aprox 7 segundos que es molesto, eso se puede sacar para que no lo muestre??

**Comment by garymartin87** [comment]
esto es de @maurocg89

**Comment by maurocg89** [comment]
Probar en apk build 6

**Comment by matiasanu** [comment]
SOLUCIONADO
