### ISSUE TITLE
El Finalizar y el Guardar quedo superpuesto

### ISSUE THREAD

**Issue by matiasanu** [garymartin87/videocallshop-api#29]
![WhatsApp Image 2019-12-30 at 11 07 50 AM](https://user-images.githubusercontent.com/50674449/71588277-a9adfb00-2aff-11ea-9668-ebb78a2240fe.jpeg)

Hola Maurito aca te envio una imagen dolde el guardar y el finalizar quedo superpuesto. Esto me paso en un momento lo capture y despues no me volvio a aparecer mas ese error mientras seguimos con la video llamada. No te asustes por la cara que esta atras de esa captura jajaja

**Comment by maurocg89** [comment]
Jajaja ese gnomo trae problemas. Probar en apk build 7 del vendedor

**Comment by matiasanu** [comment]
SOLUCIONADO
