### ISSUE TITLE
Se congelo la imagen del comprador al minimizar

### ISSUE THREAD

**Issue by matiasanu** [garymartin87/videocallshop-api#30]
![WhatsApp Image 2019-12-30 at 11 13 26 AM](https://user-images.githubusercontent.com/50674449/71588381-06111a80-2b00-11ea-917c-0f8742c321af.jpeg)

En esta quedo congelada la imagen del comprador cuando minimizo la aplicacion. Al volverla a abrir me seguia escuchando y me veia pero su imagen quedo congelada.

**Comment by maurocg89** [comment]
Esto debe ser que el celu se queda sin memoria, proba cerrando todas las apps que tengas abiertas y dejando solo la de vcs. Lo probé varias veces acá y no me pasó

**Comment by matiasanu** [comment]
Solucionado
