### ISSUE TITLE
Quedo una franja negra entre la barra de arriba y la video llamada

### ISSUE THREAD

**Issue by matiasanu** [garymartin87/videocallshop-api#31]
![WhatsApp Image 2019-12-30 at 11 13 26 AM](https://user-images.githubusercontent.com/50674449/71588466-5ee0b300-2b00-11ea-8936-0f8feff57ebd.jpeg)

**Comment by maurocg89** [comment]
Probar en apk build 6 del cliente y apk build 7 del vendedor

**Comment by matiasanu** [comment]
Maurito ahi la probe y si bien al principio de la video llamada no se ve la franja negra, si pones el celular en horizontal y lo volves a poner vertical vuelve a aparecer la franja negra, en un celular me aparecio negra y en otro blanca.

**Comment by maurocg89** [comment]
Probar en build 7 de cliente y build 8 del vendedor

**Comment by matiasanu** [comment]
Solucionado
