### ISSUE TITLE
No se puede hacer click al link de mercado pago

### ISSUE THREAD

**Issue by matiasanu** [garymartin87/videocallshop-api#32]
![WhatsApp Image 2019-12-30 at 11 16 42 AM](https://user-images.githubusercontent.com/50674449/71588571-ba12a580-2b00-11ea-8790-10450d6647b3.jpeg)

Si bien aparece el link antes de permitia hacerle click desde el mail. En este caso te lo muestra como texto y no te permite hacerle click.

**Comment by matiasanu** [comment]
![WhatsApp Image 2019-12-30 at 12 36 46 PM](https://user-images.githubusercontent.com/50674449/71588682-28576800-2b01-11ea-8662-234e0799a40f.jpeg)

No se podra poner un boton en el mail como en este ejemplo de mercado libre?

Podria decir "Pagar"

**Comment by matiasanu** [comment]
Realice una prueba hoy
![Uploading WhatsApp Image 2020-01-09 at 12.45.02 PM.jpeg…]()

Al poner Mercado de Pago me tira Hubo un Error. Si pongo cualquier otra cosa como Pago en Domicilio o Pago en tienda me cierra la orden de compra bien.

**Comment by matiasanu** [comment]
![WhatsApp Image 2020-01-09 at 12 45 02 PM](https://user-images.githubusercontent.com/50674449/72082395-da9be600-32de-11ea-9830-8f543d30207a.jpeg)

**Comment by garymartin87** [comment]
sip @matiasanu esto lo revisé la semana pasada, pensé que era una boludes pero no lo es tanto. Tampoco es algo imposible, voy a ver si mañana o el finde me hago un espacio y cierro todo.

**Comment by garymartin87** [comment]
Cerrado.
