### ISSUE TITLE
No conecta la video llamada

### ISSUE THREAD

**Issue by matiasanu** [garymartin87/videocallshop-api#35]
Hola Maurito, hice unas pruebas y lo que estuvo pasando es lo siguiente, cuando el comprador realiza una video llamada a una tienda antes que el vendedor este logueado en la tienda pasa que al cliente le figura que esta en la posicion 1. Luego cuando el vendedor se loguea ve que hay un cliente en la cola de espera, lo llama pero nunca logra conectar la video llamada y al cliente no le suena. Te paso las 2 capturas de pantallas del lado del vendedor y del clienta.

![image](https://user-images.githubusercontent.com/50674449/74682918-2e370480-51a6-11ea-9e58-e0754b036e05.png)

![image](https://user-images.githubusercontent.com/50674449/74682964-3f801100-51a6-11ea-802f-130274d983f2.png)

**Comment by garymartin87** [comment]
@matiasanu podes testarlo de nuevo ?
