### ISSUE TITLE
Push notifications para vendedor

### ISSUE THREAD

**Issue by matiasanu** [garymartin87/videocallshop-api#37]
Hoy las push estan llegando bien pero solo llegan como un mensaje hacen un solo sonido. Lo que hace que los vendedores lo tomen como un mensaje de whatsapp mientras hay un cliente esperando a ser llamado. Necesitaria que lo cambiemos como si fuera una llamada telefonica que les suene constantemente para que atiendan a esa persona que esta esperando en la fila.

**Comment by maurocg89** [comment]
Probar en build 10

**Comment by matiasanu** [comment]
Solucionado!
