### ISSUE TITLE
Mercado Pago Tienda 1. Con mi Mercado Pago Personal matiasanu@gmail.com

### ISSUE THREAD

**Issue by matiasanu** [garymartin87/videocallshop-api#46]
{"status":200,"credentials":{"access_token":"APP_USR-8649637676151674-050121-c2d037b2451fb6917553e26cc52ac6db-229357796","public_key":"APP_USR-66d6d9bc-6444-47e1-ac8b-132f5a01fd09","refresh_token":"TG-5eac923a6995a100063a052f-229357796","live_mode":true,"user_id":229357796,"token_type":"bearer","expires_in":15552000,"scope":"offline_access read write"}}

**Comment by garymartin87** [comment]
Mati esto es correcto, no es un error. Acabo de chequear y se vinculo bien en la base de datos el mercadopago.
Un vendedor de esta tienda es:
```
alemmartin@gmail.com
sonserios10
```

**Comment by matiasanu** [comment]
Si si solo te lo queria informar, no se donde van las documentaciones jeje

**Comment by matiasanu** [comment]
Y queria ver si lo habia hecho bien, ahi iba a hacer una orden de compra en stage para probarlo
