### ISSUE TITLE
El orden de la cola en la tool de la web app y en la app no es el mismo.

### ISSUE THREAD

**Issue by matiasanu** [garymartin87/videocallshop-api#58]
![image](https://user-images.githubusercontent.com/50674449/82382617-a5c53b80-9a02-11ea-904a-cdfbdc0fcf8c.png)

![image](https://user-images.githubusercontent.com/50674449/82382659-bbd2fc00-9a02-11ea-84da-e081602c277d.png)

**Comment by matiasanu** [comment]
https://videocallshop-api-stage.herokuapp.com/store-user.html?email=laelena@laelenasa.com&password=sonserios10

https://videocallshop-webapp-stage.herokuapp.com/3/create-call-request

**Comment by matiasanu** [comment]
![image](https://user-images.githubusercontent.com/50674449/82384896-3ef65100-9a07-11ea-9f9d-1534770e103c.png)
![image](https://user-images.githubusercontent.com/50674449/82384929-4f0e3080-9a07-11ea-9456-67e5143f76c5.png)
En esta otra prueba que hice en la web app sale bien y en la app sale desordenado, y no aparece la que hice con el celular en la posicion 3. Tambien esta repitiendo la 4 que fue la ultima que hice desde la web

**Comment by matiasanu** [comment]
Cuando le pones refresh en el celular cambian de orden no se mantienen siempre igual, ahora me aparecio la del celular pero en otro orden
![image](https://user-images.githubusercontent.com/50674449/82385241-04d97f00-9a08-11ea-9c6a-06af3707f78c.png)

**Comment by maurocg89** [comment]
probar en b13

**Comment by matiasanu** [comment]
Recien hice una prueba, al principio apareceio bien tanto en la web app como en la app de android. Cargue 4 clientes en La Elena del 1 al 4. Hasta ahi todo barbaro. 
Cancele la primer llamada. Y ahi en la web app me aparecio bien..
![image](https://user-images.githubusercontent.com/50674449/82604390-a092f880-9b8a-11ea-8aa5-66d78311e3d9.png)

Pero en la app se cambio el orden ya no figura 2,3 y 4. Sino 3,2 y 4.
![image](https://user-images.githubusercontent.com/50674449/82604486-c9b38900-9b8a-11ea-88db-814933dda487.png)

Cuando entre a la app del cliente que en un primer momento estaba en la posicion 3. Entre luego de cancelar la llamada numero 1, para ver si se cambiaba a posicion numero 2. Cuando entre quedo cargando un rato, me tiro hubo un error, y me llevo a la pagina de inicio. Despues hice una nueva prueba agregue un 5to desde el celular y elimine al que decia numero 2. En este caso me mostro bien que estaba 3ero en la lista de espera el cliente. Pero me volvio a desordenar la cola.

![image](https://user-images.githubusercontent.com/50674449/82605194-ec926d00-9b8b-11ea-8594-88de55953361.png)

![image](https://user-images.githubusercontent.com/50674449/82605240-fe741000-9b8b-11ea-967b-17e0ce7eaa79.png)

A; pasar un rato volvi a entrar a la cola a ver si seguia en la posicion numero 3 y me puso time out, me cerro la app de cliente y me mando al inicio nuevamente, se ve que al pasar un tiempo te saca de la espera (osea en la web app figura que sigue esperando, pero el cliente no puede ingresar nuevamente a la sala de espera)

**Comment by matiasanu** [comment]
Solucionado
